### PR TITLE
Added System Dark Mode, Updated theme settings, Persistent Vuex

### PR DESCRIPTION
**Pull request by zackbcom**
Added option for System specific dark mode.
Updated Themes to have one color palette for dark and light to align with the database.
Added confirmation for deleting a theme.

image

image

### CODE REVIEW

**Comment by zackbcom** [comment]
@hay-kot Let me know what you think with the progress. There are some edge cases I still need to fix. Like deleting the current theme, It should fall back to default.

**Comment by hay-kot** [comment]
@zackbcom  looks great so far, thanks for cleaning up my garbage!

**Comment by zackbcom** [comment]
1. Added in persistence to vuex, everything in state will rehydrate on pageRefresh / browserReload.
2. Cookie code was removed from codebase.
3. need to lock down the changing of default theme.

**Comment by zackbcom** [comment]
Updated store persistence only for the userSettings module. (Selected Theme, Darkmode Setting)

**Pull request merged**
