### PR TITLE
Update install.md

### PR DESCRIPTION
**Pull request by cklann1**
Add a tip to fix linux/arm/v7 on RP4 when getting 'Fatal Python error: init_interp_main: can't initialize time'

### CODE REVIEW

**Comment by hay-kot** [comment]
Can you set the target branch to the branch `dev`?

**Comment by cklann1** [comment]
Hi!
Any other feedback on my proposed change to address issue #249 ?

Thanks!

**Comment by hay-kot** [comment]
> Hi!
> Any other feedback on my proposed change to address issue #249 ?
> 
> Thanks!

Hey sorry about the delay. Looks like you have a minor docs update to include the tip for the Pi installation error, but it looks like you have some outdated files that are being committed as new. If you can address those to only show only your changes I'll get this merged. 

Thanks!

**Comment by cklann1** [comment]
I'm sorry, I thought I only changed the Install.md file...this is my first pull request and I'm not sure what else I should do...I guess I could close this and disregard my attempted change?

**Comment by sephrat** [comment]
It'll probably be easier if you start over from dev branch, given that it's a simple .md file to change. Make sure your fork is up-to-date too.

**Pull request closed without merging**
