### PR TITLE
fix scrape recipe error

### LINKED ISSUE #138: Import Issue - bhg.com
**Describe the bug**
Unable to import a recipe from the Better Homes and Gardens website (bhg.com) using the import recipe function.  Error is thrown and recipe is not imported.  No additional information in the logs to indicate what is happening.

**Steps To Reproduce**
Go to 'https://www.bhg.com/recipe/chicken/pepper-lime-chicken/'
Click on 'import recipe in Meali using the link above'

**Expected behavior**
Import recipe as expected

**Actual Behavior**
Error is thrown.  No information in the last_recipe.json logs.

**Screenshots**
image

**Device Information (please complete the following information):**
 - OS: Linux
 - Deployment: Docker
 - Browser: Brave
 - Version: 1.19.88

### LINKED ISSUE #145: Error when importing recipe: KeyError: '@type'
**Describe the bug**
When importing this (very excellent cookie) recipe, it never shows up in the UI. 

https://www.bettycrocker.com/recipes/ultimate-chocolate-chip-cookies/77c14e03-d8b0-4844-846d-f19304f61c57

**Steps To Reproduce**
Clicking the purple Add Link button in the bottom right, pasting the above link.

**Device Information (please complete the following information):**
 - Deployment: docker-compose.yml
 - Browser: chrome
 - Version: 0.2.0

**Additional context**
This is what appears in the `docker-compose logs`:

```
mealie    | 08-Feb-21 19:04:44 INFO: Generating Default Theme
mealie    | /usr/local/lib/python3.9/site-packages/tzlocal/unix.py:158: UserWarning: Can not find any timezone configuration, defaulting to UTC.
mealie    |   warnings.warn('Can not find any timezone configuration, defaulting to UTC.')
mealie    | 08-Feb-21 19:04:45 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
mealie    | 08-Feb-21 19:04:45 INFO: ----INIT SCHEDULE OBJECT-----
mealie    | 08-Feb-21 19:04:45 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
mealie    | 08-Feb-21 19:04:45 INFO: New Function Scheduled
mealie    | 08-Feb-21 19:04:45 INFO: None
mealie    | 08-Feb-21 19:04:45 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
mealie    | 08-Feb-21 19:04:45 INFO: New Function Scheduled
mealie    | 08-Feb-21 19:04:45 INFO: None
mealie    | 08-Feb-21 19:04:45 INFO: Added job "update_webhook_schedule" to job store "default"
mealie    | 08-Feb-21 19:04:45 INFO: Added job "backups" to job store "default"
mealie    | 08-Feb-21 19:04:45 INFO: Added job "webhooks" to job store "default"
mealie    | 08-Feb-21 19:04:45 INFO: Scheduler started
mealie    | INFO:     Started server process [1]
mealie    | 08-Feb-21 19:04:45 INFO: Started server process [1]
mealie    | INFO:     Waiting for application startup.
mealie    | 08-Feb-21 19:04:45 INFO: Waiting for application startup.
mealie    | INFO:     Application startup complete.
mealie    | 08-Feb-21 19:04:45 INFO: Application startup complete.
mealie    | INFO:     Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
mealie    | 08-Feb-21 19:04:45 INFO: Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
mealie    | Pending jobs:
mealie    |     update_webhook_schedule (trigger: interval[0:15:00], pending)
mealie    |     backups (trigger: cron[hour='0', minute='0'], pending)
mealie    | Pending jobs:
mealie    |     update_webhook_schedule (trigger: interval[0:15:00], pending)
mealie    |     backups (trigger: cron[hour='0', minute='0'], pending)
mealie    |     webhooks (trigger: cron[hour='0', minute='0'], pending)
mealie    | INFO:     192.168.1.107:34576 - "GET / HTTP/1.1" 200 OK
mealie    | INFO:     192.168.1.107:34576 - "GET /static/css/app.9d942edd.css HTTP/1.1" 200 OK
mealie    | INFO:     192.168.1.107:34576 - "GET /static/css/chunk-vendors.1e62988f.css HTTP/1.1" 200 OK
mealie    | INFO:     192.168.1.107:34580 - "GET /static/js/app.01e1a62d.js HTTP/1.1" 200 OK
mealie    | INFO:     192.168.1.107:34582 - "GET /static/js/chunk-vendors.d2529468.js HTTP/1.1" 200 OK
mealie    | INFO:     192.168.1.107:34578 - "GET /styles/global.css HTTP/1.1" 200 OK
mealie    | INFO:     192.168.1.107:34582 - "GET /api/themes/themes/default HTTP/1.1" 404 Not Found
mealie    | INFO:     192.168.1.107:34582 - "GET /api/recipes?keys=name&keys=slug&keys=image&keys=description&keys=dateAdded&keys=rating&num=100 HTTP/1.1" 200 OK
mealie    | INFO:     192.168.1.107:34576 - "GET /api/categories HTTP/1.1" 200 OK
mealie    | INFO:     192.168.1.107:34576 - "GET /static/favicon.ico HTTP/1.1" 200 OK
mealie    | 08-Feb-21 19:14:40 INFO: Recipe Scraped From Web: {'name': 'Ultimate Chocolate Chip Cookies', 'aggregateRating': {'properties': {'ratingValue': '4.5', 'ratingCount': '1254', 'bestRating': '5', 'worstRating': '1'}, '@type': 'AggregateRating'}, 'image': 'https://images-gmi-pmc.edge-generalmills.com/983f0c5a-2b13-40db-8c92-748b279bcc3f.jpg', 'recipeIngredient': ['2 1/4\ncups Gold Medal™ all-purpose flour', '1\nteaspoon baking soda', '1/2\nteaspoon salt', '1\ncup butter, softened', '3/4\ncup granulated sugar', '3/4\ncup packed brown sugar', '1\negg', '1\nteaspoon vanilla', '2\ncups semisweet chocolate chips', '1\ncup coarsely chopped nuts, if desired'], 'recipeInstructions': [{'type': 'http://schema.org/HowToStep', 'properties': {'text': 'Heat oven to 375°F. In small bowl, mix flour, baking soda and salt; set aside.'}}, {'type': 'http://schema.org/HowToStep', 'properties': {'text': 'In large bowl, beat softened butter and sugars with electric mixer on medium speed, or mix with spoon about 1 minute or until fluffy, scraping side of bowl occasionally.'}}, {'type': 'http://schema.org/HowToStep', 'properties': {'text': 'Beat in egg and vanilla until smooth. Stir in flour mixture just until blended (dough will be stiff). Stir in chocolate chips and nuts.'}}, {'type': 'http://schema.org/HowToStep', 'properties': {'text': 'Onto ungreased cookie sheets, drop dough by rounded tablespoonfuls 2 inches apart.'}}, {'type': 'http://schema.org/HowToStep', 'properties': {'text': 'Bake 8 to 10 minutes or until light brown (centers will be soft). Cool 2 minutes; remove from cookie sheet to cooling rack. Cool completely, about 30 minutes. Store covered in airtight container.'}}], 'nutrition': {'properties': {'calories': '120 ', 'carbohydrateContent': '16 g', 'cholesterolContent': '15 mg', 'fatContent': '1 ', 'fiberContent': '0 g', 'proteinContent': '1 g', 'saturatedFatContent': '3 1/2 g', 'servingSize': '1 Cookie ', 'sodiumContent': '85 mg', 'sugarContent': '10 g', 'transFatContent': '0 g'}, '@type': 'NutritionInformation'}, 'totalTime': datetime.timedelta(seconds=5400), 'prepTime': datetime.timedelta(seconds=900), 'recipeYield': '48', '@context': 'http://schema.org', '@type': 'Recipe'}
mealie    | INFO:     192.168.1.107:34762 - "POST /api/recipes/create-url HTTP/1.1" 500 Internal Server Error
mealie    | ERROR:    Exception in ASGI application
mealie    | Traceback (most recent call last):
mealie    |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
mealie    |     result = await app(self.scope, self.receive, self.send)
mealie    |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
mealie    |     return await self.app(scope, receive, send)
mealie    |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
mealie    |     await super().__call__(scope, receive, send)
mealie    |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
mealie    |     await self.middleware_stack(scope, receive, send)
mealie    |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
mealie    |     raise exc from None
mealie    |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
mealie    |     await self.app(scope, receive, _send)
mealie    |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
mealie    |     raise exc from None
mealie    |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
mealie    |     await self.app(scope, receive, sender)
mealie    |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
mealie    |     await route.handle(scope, receive, send)
mealie    |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
mealie    |     await self.app(scope, receive, send)
mealie    |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
mealie    |     response = await func(request)
mealie    |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
mealie    |     raw_response = await run_endpoint_function(
mealie    |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
mealie    |     return await run_in_threadpool(dependant.call, **values)
mealie    |   File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
mealie    |     return await loop.run_in_executor(None, func, *args)
mealie    |   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
mealie    |     result = self.fn(*self.args, **self.kwargs)
mealie    |   File "./routes/recipe/recipe_crud_routes.py", line 29, in parse_recipe_url
mealie    |     recipe = create_from_url(url.url)
mealie    |   File "./services/scrape_services.py", line 195, in create_from_url
mealie    |     recipe_data = process_recipe_url(url)
mealie    |   File "./services/scrape_services.py", line 189, in process_recipe_url
mealie    |     new_recipe = extract_recipe_from_html(r.text, url)
mealie    |   File "./services/scrape_services.py", line 138, in extract_recipe_from_html
mealie    |     new_recipe = normalize_data(new_recipe)
mealie    |   File "./services/scrape_services.py", line 98, in normalize_data
mealie    |     recipe_data["recipeInstructions"] = normalize_instructions(
mealie    |   File "./services/scrape_services.py", line 52, in normalize_instructions
mealie    |     return [
mealie    |   File "./services/scrape_services.py", line 55, in <listcomp>
mealie    |     if step["@type"] == "HowToStep"
mealie    | KeyError: '@type'
```

I remember this happened on the last release, I think I ended up skipping this particular recipe. The new UI looks fresh, btw. Great job :smiley:

### PR DESCRIPTION
**Pull request by wengtad**
- Fixes #138 
- Fixes #145

### CODE REVIEW

**Comment by wengtad** [comment]
- Fixes #73 as well

**Comment by hay-kot** [comment]
Great Work!

**Comment by ptoulouse** [comment]
I tested it and it still not working for the example provided in #73

**Comment by hay-kot** [comment]
> I tested it and it still not working for the example provided in #73

Looks like there was a typo keeping it from working on "HowToSteps". I was able to get it working. Will do some more testing and get it merged with the next version. Thanks for letting me know!

**Pull request merged**
