### PR TITLE
Shopping list fixes

### LINKED ISSUE #356: Grouped shopping list adds duplicate items
**Describe the bug**

In the meal plan view, after clicking the 'Shopping List' button then 'GROUP (BETA)' items are grouped as expected. However, if you click away from the shopping list dialog, then open it again by again clicking 'Shopping List' all the entries are duplicated. You can repeat many times and many duplicate entries are listed. They only show in the GROUP (BETA) view and do not appear there after refreshing the page or leaving the planner view and returning

**Steps To Reproduce**
Please be specific!
1. Go to planner
2. Create a new meal plan
3. Click the Shopping List on the new card
4. Click 'GROUP (BETA)'
5. Click away from the shopping list dialog
6. Re open the shopping list dialog from the card

**Device Information (please complete the following information):**
 - OS: Debian buster
 - Deployment: docker
 - Browser: chrome
 - Version: 0.4.3

### PR DESCRIPTION
**Pull request by sephrat**
- Fix a dev issue
- Fixes #356

### CODE REVIEW

**Comment by hay-kot** [comment]
What was the dev issue?

**Comment by sephrat** [comment]
The shopping list was broken due to https://github.com/hay-kot/mealie/commit/61e0a521008d4be895b3a7e7571cf58a6eac808e#diff-dbad54e0e731f42621307b06eb796391e2dc9e8d9f827d3dba865fb958ed4fb4

**Comment by sephrat** [comment]
Now I'm not sure if snake casing the json result was intentional or not. The norm seems to be camelCase elsewhere. Should I change this?

**Comment by hay-kot** [comment]
> Now I'm not sure if snake casing the json result was intentional or not. The norm seems to be camelCase elsewhere. Should I change this?

It was not intentional, I must have broken the response when I refactored to snake case, It's likely going to require more than just a rename so I can take a look at it. 

I had thought "Fix dev issue" was in reference to something wrong with the development server, as I had recently made changes so I assumed broke something. 

Thanks again for all the PRs!

**Comment by sephrat** [comment]
> I had thought "Fix dev issue" was in reference to something wrong with the development server, as I had recently made changes so I assumed I broke something.
Yeah sorry I could hardly be less creative with such a description! It wasn't as bad as it looked :-)

**Pull request merged**
